### PR TITLE
Add button to start a new proof

### PR DESCRIPTION
**Pull request by raulpy271**
Check the result: [https://raulpy271.github.io/fitchjs/](https://raulpy271.github.io/fitchjs/)

Problem description: #1

### CODE REVIEW

**Comment by mrieppel** [comment]
The cod you have looks good, and thanks for fixing the google font issue
too.  One request, though: the "New Proof" button is right next to the
"Append" button, so I worry that it would be very easy for someone to
accidentally start a new proof and erase all their work when they simply
meant to append a line.  (Also someone might think the button is used to
begin a new subproof, rather than restarting the whole proof.)  What do you
think about putting the button somewhere more out of the way?  Like below
the blue drvd div for example?

**Comment by raulpy271** [comment]
I agree with you, so I think that putting the element below the blue div is a good choice. Also, I guess that centered is more pretty. What do you think? And about the name 'New proof', do you have a better option?

**Comment by mrieppel** [comment]
Yes you could center it under the blue div, or left align below the "Click
the 'Reference' tab for ..." instructions.  "New Proof" is fine,  "Start
New Proof"  could work too.

**Comment by raulpy271** [comment]
What version do you think it's better? I think that's the first.

Screenshot from 2021-03-05 15-00-29

Screenshot from 2021-03-05 15-06-08

**Comment by raulpy271** [comment]
"Start new proof" is a good name, I'll use it

**Comment by mrieppel** [comment]
I like the button at the bottom, I think that makes it clearer that it has
a different function and isn't used for inputting lines into the proof.

**Comment by raulpy271** [comment]
I guess that I disagree with you, but no problem, I'll use the second version.

**Comment by raulpy271** [comment]
I fixed the button position. Looks good?

**Comment by mrieppel** [comment]
Sure that looks good.

**Pull request merged**
